import { defineConfig } from 'umi';

enum Type {
  HOME = 'home',
  PAGE = 'page',
  POST = 'post',
}
enum Mark {
  PAGE = 'page',
  TAG = 'tag',
  CATEGORY = 'category',
  ARCHIVE = 'archive',
}

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  antd: false,
  routes: [
    {
      path: '/',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-首页",
      wrappers: ['@/layout/index'],
      type: Type.HOME,
      mark: Mark.PAGE,
    },
    {
      path: '/pages/:page',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-文章",
      wrappers: ['@/layout/index'],
      type: Type.HOME,
      mark: Mark.PAGE,
    },
    {
      path: '/tags',
      component: '@/pages/Tags/index',
      exact: true,
      title: "liangerwen's☻Blog-标签",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
    },
    {
      path: '/tags/:id',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-标签",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
      mark: Mark.TAG,
    },
    {
      path: '/tags/:id/:page',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-标签",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
      mark: Mark.TAG,
    },
    {
      path: '/categories',
      component: '@/pages/Categories/index',
      exact: true,
      title: "liangerwen's☻Blog-分类",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
    },
    {
      path: '/categories/:id',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-分类",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
      mark: Mark.CATEGORY,
    },
    {
      path: '/categories/:id/:page',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-分类",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
      mark: Mark.CATEGORY,
    },
    {
      path: '/archives',
      component: '@/pages/Archives/index',
      exact: true,
      title: "liangerwen's☻Blog-归档",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
    },
    {
      path: '/archives/page/:page',
      component: '@/pages/Archives/index',
      exact: true,
      title: "liangerwen's☻Blog-归档",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
    },
    {
      path: '/archives/:id',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-归档",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
      mark: Mark.ARCHIVE,
    },
    {
      path: '/archives/:id/:page',
      component: '@/pages/Home/index',
      exact: true,
      title: "liangerwen's☻Blog-归档",
      wrappers: ['@/layout/index'],
      type: Type.PAGE,
      mark: Mark.ARCHIVE,
    },
    // {
    //   path: '/about',
    //   component: '@/pages/About/index',
    //   exact: true,
    //   title: "liangerwen's☻Blog-关于",
    //   wrappers: ['@/layout/index'],
    //   type: Type.PAGE,
    // },
    // {
    //   path: '/message',
    //   component: '@/pages/Message/index',
    //   exact: true,
    //   title: "liangerwen's☻Blog-留言",
    //   wrappers: ['@/layout/index'],
    //   type: Type.PAGE,
    // },
    {
      path: '/posts/:id',
      component: '@/pages/Post/index',
      title: "liangerwen's☻Blog-文章",
      wrappers: ['@/layout/index'],
      type: Type.POST,
    },
    {
      path: '*',
      component: '@/pages/404/index',
      title: "liangerwen's☻Blog-页面未找到",
    },
  ],
  devServer: { port: 8888 },
  fastRefresh: {},
});
